const mockUser = {
  login: "yungsters",
  id: 55161,
  node_id: "MDQ6VXNlcjU1MTYx",
  avatar_url: "https://avatars.githubusercontent.com/u/55161?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yungsters",
  html_url: "https://github.com/yungsters",
  followers_url: "https://api.github.com/users/yungsters/followers",
  following_url:
    "https://api.github.com/users/yungsters/following{/other_user}",
  gists_url: "https://api.github.com/users/yungsters/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yungsters/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yungsters/subscriptions",
  organizations_url: "https://api.github.com/users/yungsters/orgs",
  repos_url: "https://api.github.com/users/yungsters/repos",
  events_url: "https://api.github.com/users/yungsters/events{/privacy}",
  received_events_url: "https://api.github.com/users/yungsters/received_events",
  type: "User",
  site_admin: false,
  contributions: 129,
};

const mockLabel = {
  id: 791921801,
  node_id: "MDU6TGFiZWw3OTE5MjE4MDE=",
  url: "https://api.github.com/repos/facebook/react/labels/%E2%9D%A4%EF%B8%8F",
  name: "❤️",
  color: "ffffff",
  default: false,
  description: "",
};

const mockAssignees = [
  {
    login: "mockuser1",
    id: 101,
    node_id: "MDQ6VXNlcjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/101?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mockuser1",
    html_url: "https://github.com/mockuser1",
    followers_url: "https://api.github.com/users/mockuser1/followers",
    following_url:
      "https://api.github.com/users/mockuser1/following{/other_user}",
    gists_url: "https://api.github.com/users/mockuser1/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mockuser1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mockuser1/subscriptions",
    organizations_url: "https://api.github.com/users/mockuser1/orgs",
    repos_url: "https://api.github.com/users/mockuser1/repos",
    events_url: "https://api.github.com/users/mockuser1/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mockuser1/received_events",
    type: "User",
    site_admin: false,
  },
];

const mockIssues = [
  {
    url: "https://api.github.com/repos/facebook/react/issues/27793",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/27793/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/27793/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/27793/events",
    html_url: "https://github.com/facebook/react/issues/27793",
    id: 2025054179,
    node_id: "I_kwDOAJy2Ks54s9_j",
    number: 27793,
    title:
      "Feature: useEffectEvent should be useCallback without dependency array",
    user: {
      login: "kuchta",
      id: 903277,
      node_id: "MDQ6VXNlcjkwMzI3Nw==",
      avatar_url: "https://avatars.githubusercontent.com/u/903277?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kuchta",
      html_url: "https://github.com/kuchta",
      followers_url: "https://api.github.com/users/kuchta/followers",
      following_url:
        "https://api.github.com/users/kuchta/following{/other_user}",
      gists_url: "https://api.github.com/users/kuchta/gists{/gist_id}",
      starred_url: "https://api.github.com/users/kuchta/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kuchta/subscriptions",
      organizations_url: "https://api.github.com/users/kuchta/orgs",
      repos_url: "https://api.github.com/users/kuchta/repos",
      events_url: "https://api.github.com/users/kuchta/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/kuchta/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 5,
    created_at: "2023-12-05T00:30:27Z",
    updated_at: "2023-12-13T13:27:07Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "The experimental useEffectEvent is generally something useCallback should have been without depedency array or with empty dependency array to match the behavior of useEffect. Introducing new name will just bring more confusion since it's very hard to image, what useEffectEvent should do...🙏🏻✌🏻👀",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/27793/reactions",
      total_count: 1,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 1,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/27793/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/27629",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/27629/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/27629/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/27629/events",
    html_url: "https://github.com/facebook/react/pull/27629",
    id: 1969368879,
    node_id: "PR_kwDOAJy2Ks5eLKV_",
    number: 27629,
    title: "[Possible bug] Sibling tree blocked during PPR resume",
    user: {
      login: "acdlite",
      id: 3624098,
      node_id: "MDQ6VXNlcjM2MjQwOTg=",
      avatar_url: "https://avatars.githubusercontent.com/u/3624098?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/acdlite",
      html_url: "https://github.com/acdlite",
      followers_url: "https://api.github.com/users/acdlite/followers",
      following_url:
        "https://api.github.com/users/acdlite/following{/other_user}",
      gists_url: "https://api.github.com/users/acdlite/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/acdlite/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/acdlite/subscriptions",
      organizations_url: "https://api.github.com/users/acdlite/orgs",
      repos_url: "https://api.github.com/users/acdlite/repos",
      events_url: "https://api.github.com/users/acdlite/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/acdlite/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: "",
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-10-30T23:14:46Z",
    updated_at: "2023-10-30T23:24:30Z",
    closed_at: null,
    author_association: "COLLABORATOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/27629",
      html_url: "https://github.com/facebook/react/pull/27629",
      diff_url: "https://github.com/facebook/react/pull/27629.diff",
      patch_url: "https://github.com/facebook/react/pull/27629.patch",
      merged_at: null,
    },
    body: "Demonstrates a (possible) bug in PPR, based on an issue I found while testing out PPR in Next.js\r\n\r\nThe issue arises when, during a resume, a component that's part of the static prelude suspends while being replayed (we replay prerendered components if they are the parent of a dynamic slot). In the test case I found, the suspended parent is blocking an unrelated sibling Suspense tree from rendering.\r\n\r\nSee the test case I wrote for a detailed step-by-step explanation.\r\n\r\nThis is arguably an esoteric issue because the parent component's data should be cached. However, even if the data is cached, loading the data from cache can still be async. It's a known part of the design that this creates a (short-lived) waterfall along the parent path of the dynamic slot — but in principle, we should avoid waterfalls between parallel Suspense trees.\r\n\r\nI suspect it's some small quirk of the implementation that can be fixed without much trouble.",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/27629/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/27629/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
];

export { mockUser, mockAssignees, mockIssues, mockLabel };
